## Cocoa Economy Data

In [2]:
# Imports
import panel as pn
pn.extension('plotly')
import plotly.express as px
import pandas as pd
import hvplot.pandas
import matplotlib.pyplot as plt
import numpy as np
import os
from pathlib import Path
from dotenv import load_dotenv

import warnings
warnings.filterwarnings('ignore')
%matplotlib inline

In [9]:
# Load data
cocoa_economy_data = Path('/Users/erahm/Downloads/FAOSTAT_cocoa_trade_matrix.csv')

In [10]:
# View a sample of the data for AAPL Historical.
cocoa_economy_data = pd.read_csv('/Users/erahm/Downloads/FAOSTAT_cocoa_trade_matrix.csv')
cocoa_economy_data

,Domain Code,Domain,Reporter Country Code (FAO),Reporter Countries,Partner Country Code (FAO),Partner Countries,Element Code,Element,Item Code,Item,Year Code,Year,Unit,Value,Flag,Flag Description
0,TM,Detailed trade matrix,32,Cameroon,68,France,5910,Export Quantity,661,"Cocoa, beans",2010,2010,tonnes,0.0,NaN,Official data
1,TM,Detailed trade matrix,32,Cameroon,68,France,5910,Export Quantity,661,"Cocoa, beans",2011,2011,tonnes,0.0,NaN,Official data
2,TM,Detailed trade matrix,32,Cameroon,68,France,5910,Export Quantity,661,"Cocoa, beans",2014,2014,tonnes,3199.0,NaN,Official data
3,TM,Detailed trade matrix,32,Cameroon,68,France,5910,Export Quantity,661,"Cocoa, beans",2015,2015,tonnes,3773.0,NaN,Official data
4,TM,Detailed trade matrix,32,Cameroon,68,France,5910,Export Quantity,661,"Cocoa, beans",2016,2016,tonnes,0.0,NaN,Official data
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1583,TM,Detailed trade matrix,159,Nigeria,231,United States of America,5922,Export Value,665,"Cocoa, powder & cake",2015,2015,1000 US$,91.0,*,Unofficial figure
1584,TM,Detailed trade matrix,159,Nigeria,231,United States of America,5922,Export Value,665,"Cocoa, powder & cake",2016,2016,1000 US$,NaN,NaN,Official data
1585,TM,Detailed trade matrix,159,Nigeria,231,United States of America,5922,Export Value,665,"Cocoa, powder & cake",2017,2017,1000 US$,7.0,*,Unofficial figure
1586,TM,Detailed trade matrix,159,Nigeria,231,United States of America,5922,Export Value,665,"Cocoa, powder & cake",2018,2018,1000 US$,350.0,R,Estimated data using trading partners database
1587,TM,Detailed trade matrix,159,Nigeria,231,United States of America,5922,Export Value,665,"Cocoa, powder & cake",2019,2019,1000 US$,50.0,*,Unofficial figure

In [25]:
# Create Cocoa Economy Data DataFrame
cocoa_economy_data_df = pd.DataFrame(cocoa_economy_data)
cocoa_economy_data_df

,Domain Code,Domain,Reporter Country Code (FAO),Reporter Countries,Partner Country Code (FAO),Partner Countries,Element Code,Element,Item Code,Item,Year Code,Year,Unit,Value,Flag,Flag Description
0,TM,Detailed trade matrix,32,Cameroon,68,France,5910,Export Quantity,661,"Cocoa, beans",2010,2010,tonnes,0.0,NaN,Official data
1,TM,Detailed trade matrix,32,Cameroon,68,France,5910,Export Quantity,661,"Cocoa, beans",2011,2011,tonnes,0.0,NaN,Official data
2,TM,Detailed trade matrix,32,Cameroon,68,France,5910,Export Quantity,661,"Cocoa, beans",2014,2014,tonnes,3199.0,NaN,Official data
3,TM,Detailed trade matrix,32,Cameroon,68,France,5910,Export Quantity,661,"Cocoa, beans",2015,2015,tonnes,3773.0,NaN,Official data
4,TM,Detailed trade matrix,32,Cameroon,68,France,5910,Export Quantity,661,"Cocoa, beans",2016,2016,tonnes,0.0,NaN,Official data
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1583,TM,Detailed trade matrix,159,Nigeria,231,United States of America,5922,Export Value,665,"Cocoa, powder & cake",2015,2015,1000 US$,91.0,*,Unofficial figure
1584,TM,Detailed trade matrix,159,Nigeria,231,United States of America,5922,Export Value,665,"Cocoa, powder & cake",2016,2016,1000 US$,NaN,NaN,Official data
1585,TM,Detailed trade matrix,159,Nigeria,231,United States of America,5922,Export Value,665,"Cocoa, powder & cake",2017,2017,1000 US$,7.0,*,Unofficial figure
1586,TM,Detailed trade matrix,159,Nigeria,231,United States of America,5922,Export Value,665,"Cocoa, powder & cake",2018,2018,1000 US$,350.0,R,Estimated data using trading partners database
1587,TM,Detailed trade matrix,159,Nigeria,231,United States of America,5922,Export Value,665,"Cocoa, powder & cake",2019,2019,1000 US$,50.0,*,Unofficial figure

In [52]:
#econ_path = Path('/Users', 'tylerhubbard', 'umnfintech', 'project1_group3', 'Resources', 'FAOSTAT_food_insecurity.csv')
#cocoa_economy_data_df = pd.read_csv(cocoa_economy_data , index_col=['Item', 'Area', 'Year'])
cocoa_economy_data_df = cocoa_economy_data_df.drop(columns=['Domain Code', 'Domain', 'Area Code (FAO)', 'Element Code',
                                'Item Code', 'Year Code', 'Flag', 'Flag Description', 'Element'])
                                index=['Cocoa, beans', 'Cocoa, butter', 'Cocoa, paste', 'Cocoa, powder & cake'
                                ])
cocoa_economy_data_df.head()

IndentationError: unexpected indent (Temp/ipykernel_7652/1673830961.py, line 5)

In [ ]:
econ_path = Path('/Users', 'tylerhubbard', 'umnfintech', 'project1_group3', 'Resources', 'FAOSTAT_food_insecurity.csv')
econ_df = pd.read_csv(econ_path, index_col=['Item', 'Area', 'Year'])
econ_df = econ_df.drop(columns=['Domain Code', 'Domain', 'Area Code (FAO)', 'Element Code',
                                'Item Code', 'Year Code', 'Flag', 'Flag Description', 'Note', 'Element'],
                      index=['Average value of food production (constant 2004-2006 I$/cap) (3-year average)',
                      'Cereal import dependency ratio (percent) (3-year average)',
                            'Prevalence of undernourishment (percent) (3-year average)',
                            'Percent of arable land equipped for irrigation (percent) (3-year average)',
                            'Percentage of population using at least basic drinking water services (percent)',
                            'Percentage of population using safely managed drinking water services (Percent)'
                            ])
econ_df.head(60)